### ISSUE TITLE
It's a very nice work. But I have a suggestion.

### ISSUE THREAD

**Issue by zhaohaiyang01** [ORNL/PDMATLAB2D#7]
I am a beginner in the field of PD, I think this code is very help for me to learn the theory of peridynamics. But I suggest Indicating the version of Matlab programming codes. Because in the running process, I met an error “Unrecognized function or variable ***”(Such as the built-in function ‘clim’ Line 87 in function “PlotField”). In fact, it's only called 'clim' in the version Matlab 2022a, and it's called 'caxis' in the lower version. I hope this method solving the minor error can help other friends that run this codes.

**Comment by streeve** [comment]
Thanks for pointing this out - @pabloseleson  can you check/add version requirements to the documentation and potentially increase support for older versions?

**Comment by pabloseleson** [comment]
Thank you for the comment. We were waiting for the paper release to address this issue. We have added support in the PlotFIeld.m function to MATLAB versions before 2022a (see: commit 5e2e87572d0c9fed5fcd520caad62fd47c71f297).
